# -*- coding: utf-8 -*-
from process import CONFIGURATION

###########################################################
#######  COFIGURATION
###########################################################

SEC_NAME = CONFIGURATION["SNMP"]["SEC_NAME"]
SEC_LEVEL = CONFIGURATION["SNMP"]["SEC_LEVEL"]
PRIVATE_PROTO = CONFIGURATION["SNMP"]["PRIVATE_PROTO"]
PRIVATE_PASS = CONFIGURATION["SNMP"]["PRIVATE_PASS"]
AUTH_PROTO = CONFIGURATION["SNMP"]["AUTH_PROTO"]
AUTH_PASS = CONFIGURATION["SNMP"]["AUTH_PASS"]
COMUNIDAD = CONFIGURATION["SNMP"]["COMUNIDAD"]
DIRECTORY_LAST_DATA = CONFIGURATION["SNMP"]["DIRECTORY_LAST_DATA"]
DIRECTORY_DATA = CONFIGURATION["SNMP"]["DIRECTORY_DATA"]
DIRECTORY_NET_DATA = CONFIGURATION["SNMP"]["DIRECTORY_NET_DATA"]
DIRECTORY_RED_CORP_DEVICES_DATA = CONFIGURATION["SNMP"]["DIRECTORY_RED_CORP_DEVICES_DATA"]
