# -*- coding: utf-8 -*-
from process import CONFIGURATION

###########################################################
#######  COFIGURATION
###########################################################

DB_CONFIGURATION_STRING = CONFIGURATION["DB_SQLLITE"]["URL_SQLLITE"]

DB_CONFIGURATION_IP = CONFIGURATION["DB_CONFIGURATION"]["IP"]
DB_CONFIGURATION_PORT = CONFIGURATION["DB_CONFIGURATION"]["PORT"]
DB_CONFIGURATION_USER = CONFIGURATION["DB_CONFIGURATION"]["USER"]
DB_CONFIGURATION_PASS = CONFIGURATION["DB_CONFIGURATION"]["PASSWORD"]
DB_CONFIGURATION_DB = CONFIGURATION["DB_CONFIGURATION"]["DB"]
